<?php

namespace OC\PlatformBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{

	public function getApplicationsWithAdvert($limit)
	{
		$qb = $this->createQueryBuilder('a');

		$qb ->join('a.advert', 'adv')
			->addSelect('adv');

		$qb->setMaxResults($limit);
		
		return $qb->getQuery()
				  ->getResult();	
	}	
	
  public function isFlood($ip, $secondes)
  {
    $qb = $this->createQueryBuilder('c')
               ->select('COUNT(c)')
               ->where('c.ip = :ip')
                 ->setParameter('ip', $ip)
               ->andWhere('c.date >= :date')
                 ->setParameter('date', new \Datetime('-'.$secondes.'seconds'));
    return (bool) $qb->getQuery()->getSingleScalarResult();
  }

}
