<?php

namespace OC\PlatformBundle\Entity;

/**
 * ApplicationNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
